### ISSUE TITLE
model stopped oscillation

### ISSUE THREAD

**Issue by Amirreza-Mousavi** [luciansmith/network-modeling-2021-example#8]
should we edit the strings ?

k0=50;
k4=80;

**Comment by luciansmith** [comment]
You found the correct commit, but as it turns out, the problem was due to only one of the changes (to k0) and not the change to k4.  You'll find that a lot in other situations:  you'll be able to find the change that broke things, but only a part of the change was a problem.  So the next step after finding the problematic whole commit will be finding the problematic actual change.

Good job finding the problem!
